---
- name: Install nginx and policycoreutils-python-utils
  ansible.builtin.dnf:
    name:
      - nginx
      - policycoreutils-python-utils
    state: present

- name: Update nginx service template
  ansible.builtin.template:
    src: nginx@.service
    dest: /etc/systemd/system/nginx@.service
    owner: root
    group: root
    mode: '0644'

- name: Configure nginx instance {{ nginx_instance }}
  ansible.builtin.template:
    src: nginx-{{ nginx_instance }}.conf
    dest: /etc/nginx/nginx-{{ nginx_instance }}.conf
    lstrip_blocks: true
    owner: root
    group: root
    mode: '0644'
  notify: Reload service nginx@{{ nginx_instance }}

- name: Allow nginx to listen on tcp port via SELinux
  community.general.seport:
    ports: '{{ item }}'
    proto: tcp
    setype: http_port_t
    state: present
  loop: '{{ nginx_multinstance[nginx_instance].ports }}'

- name: Start service nginx@{{ nginx_instance }}
  ansible.builtin.systemd:
    name: nginx@{{ nginx_instance }}.service
    state: started
    enabled: true
    daemon_reload: true
  ignore_errors: '{{ ansible_check_mode }}'
